name:                highlighter
version:             0.2.3.0
github:              "madf/highlighter"
license:             BSD-3-Clause
author:
- "Alex Suraci"
- "Maksym Mamontov"
maintainer:
- "i.am@toogeneric.com"
- "madf@madf.info"
copyright:           "2025 Alex Suraci, Maksym Mamontov"
license-file:        LICENSE

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Processes source code using tons of lexers, tokenizing it and formatting it as e.g. HTML.
  .
  Very similar to the Python Pygments library; many lexers directly converted from it.

flags:
  executable:
    description: Install a "highlighter" executable for highlighting source code as HTML.
    default: false
    manual: false

dependencies:
- base >= 4.7 && < 5
- blaze-html
- blaze-markup
- bytestring
- filepath
- mtl
- pcre-light
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  OverloadedStrings

library:
  source-dirs: src

executables:
  highlighter:
    when:
      - condition: flag(executable)
        then:
          buildable: true
        else:
          buildable: false
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - highlighter
